//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost:5254";
    }

    /**
     * @return Success
     */
    aurionCalApiEndpointsCheckLoginInfoEndpoint(checkLoginInfoRequest: AurionCalApiEndpointsCheckLoginInfoRequest): Promise<AurionCalApiEndpointsCheckLoginInfoResponse> {
        let url_ = this.baseUrl + "/api/check-aurion-auth";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(checkLoginInfoRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAurionCalApiEndpointsCheckLoginInfoEndpoint(_response);
        });
    }

    protected processAurionCalApiEndpointsCheckLoginInfoEndpoint(response: Response): Promise<AurionCalApiEndpointsCheckLoginInfoResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AurionCalApiEndpointsCheckLoginInfoResponse;
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as FastEndpointsErrorResponse;
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AurionCalApiEndpointsCheckLoginInfoResponse>(null as any);
    }

    /**
     * @return No Content
     */
    aurionCalApiEndpointsDeleteUserEndpoint(): Promise<void> {
        let url_ = this.baseUrl + "/api/user/delete";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAurionCalApiEndpointsDeleteUserEndpoint(_response);
        });
    }

    protected processAurionCalApiEndpointsDeleteUserEndpoint(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return No Content
     */
    aurionCalApiEndpointsGetCalendarFeedEndpoint(userId: string, token: string): Promise<void> {
        let url_ = this.baseUrl + "/api/calendar/{userId}/{token}.ics";
        if (userId === undefined || userId === null)
            throw new globalThis.Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        if (token === undefined || token === null)
            throw new globalThis.Error("The parameter 'token' must be defined.");
        url_ = url_.replace("{token}", encodeURIComponent("" + token));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAurionCalApiEndpointsGetCalendarFeedEndpoint(_response);
        });
    }

    protected processAurionCalApiEndpointsGetCalendarFeedEndpoint(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    aurionCalApiEndpointsGetUserProfileEndpoint(): Promise<AurionCalApiEndpointsUserProfileResponse> {
        let url_ = this.baseUrl + "/api/user/profile";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAurionCalApiEndpointsGetUserProfileEndpoint(_response);
        });
    }

    protected processAurionCalApiEndpointsGetUserProfileEndpoint(response: Response): Promise<AurionCalApiEndpointsUserProfileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AurionCalApiEndpointsUserProfileResponse;
            return result200;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AurionCalApiEndpointsUserProfileResponse>(null as any);
    }

    /**
     * @return Success
     */
    aurionCalApiEndpointsRegisterUserEndpoint(registerUserRequest: AurionCalApiEndpointsRegisterUserRequest): Promise<AurionCalApiEndpointsRegisterUserResponse> {
        let url_ = this.baseUrl + "/api/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(registerUserRequest);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAurionCalApiEndpointsRegisterUserEndpoint(_response);
        });
    }

    protected processAurionCalApiEndpointsRegisterUserEndpoint(response: Response): Promise<AurionCalApiEndpointsRegisterUserResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as AurionCalApiEndpointsRegisterUserResponse;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<AurionCalApiEndpointsRegisterUserResponse>(null as any);
    }

    /**
     * @return No Content
     */
    aurionCalApiEndpointsResetCalendarTokenEndpoint(): Promise<void> {
        let url_ = this.baseUrl + "/api/user/reset-calendar-token";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAurionCalApiEndpointsResetCalendarTokenEndpoint(_response);
        });
    }

    protected processAurionCalApiEndpointsResetCalendarTokenEndpoint(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface AurionCalApiEndpointsCheckLoginInfoResponse {
    isValid?: boolean;
    message?: string;
    token?: string;
}

/** the dto used to send an error response to the client */
export interface FastEndpointsErrorResponse {
    /** the http status code sent to the client. default is 400. */
    statusCode?: number;
    /** the message for the error response */
    message?: string;
    /** the collection of errors for the current context */
    errors?: { [key: string]: string[]; };
}

export interface AurionCalApiEndpointsCheckLoginInfoRequest {
    email: string;
    password: string;
}

export interface AurionCalApiEndpointsGetCalendarFeedRequest {
}

export interface AurionCalApiEndpointsUserProfileResponse {
    userId?: string;
    email?: string;
    calendarFeedUrl?: string;
}

export interface AurionCalApiEndpointsRegisterUserResponse {
    userId?: string;
}

export interface AurionCalApiEndpointsRegisterUserRequest {
    email?: string;
    password?: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}